name: CI Test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19'
      - run:  go test ./... -tags=unit -v
      - run:  go test ./... -tags=e2e -v
